---
# This is probably best if you don't change the default value.
shardCount: 1

# Default prefixes of ThotPatrol. This is permanent, i.e., once set, it'll stay
# the same until the database is deleted.
# Although, you can use the `setPrefix` command to change server speific prefix.
prefix:
  - "tp!"

# Default status of ThotPatrol.
# Valid values are `online`, `idle`, `dnd` and `invisible`/
status: "online"

# Default activity of ThotPatrol.
game:
  # Activity type.
  # Valid values are `Playing`, `Listening`, `Watching` and `Streaming`.
  # Note that `Streaming` activity will only work in a valid Twitch channel URL
  # is added in the `url` field below.
  type: "Playing"
  # Activity names.
  # Strings you add here will be randomly rotated in the interval specified
  # in the `interval` field below.
  name:
    - "with ThotPatrol Users."
    - "with Thots on this Discord Server."
    - "tp!help"
  # Twitch channel URL for Streaming activity.
  url: "https://twitch.tv/#"
  # Activity name rotation interval (in minutes).
  interval: 1

# Music settings
music:
  # Should ThotPatrol show the name of the song it's currently playing as its
  # activity?
  status: true
  # How many passes ThotPatrol dispatcher should take when sending packets to
  # reduce packet loss for music. Values over 5 aren't recommended, as it means
  # you are using 5x more bandwidth.
  passes: 1

# Log level for ThotPatrol's logging. A lower value means less clutter in the
# console and a higher value means more details in the console.
# Valid values ranges from 1 - 6
logLevel: 6
